name: Nuget Publish brandedoutcast action 

on:
  push:
    branches: [ main1 ]
  pull_request:
    branches: [ main1 ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    
    - name: Install dependencies
      run: dotnet restore  ./blazor-server-githubactions-demo.csproj
    - name: Build
      run: dotnet build ./blazor-server-githubactions-demo.csproj --configuration Release --no-restore
       
    - name: Pack nugets
      run: dotnet pack  --no-build -c Release ./blazor-server-githubactions-demo.csproj -o .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols --skip-duplicate
