# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy .Net Core app to Azure Web App - devblazorsvr-ga-demoss

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore 
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
  DeployDev:

      name: Deploy to Dev 
      if: github.event_name == 'pull_request'
      needs: [build]
      runs-on: ubuntu-latest
      environment: 
       name: Development
       url: 'http://devvenftappserver.azurewebsites.net'
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'devvenftappserver'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_DEV }}
          package: . 
     
  DeployStaging:

      name: Deploy to Staging 
      if: github.event.ref == 'refs/heads/main'
      needs: [build]
      runs-on: ubuntu-latest
      environment: 
       name: Staging
       url: 'https://stagingvenftappserver.azurewebsites.net'
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'stagingvenftappserver'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_STAGING }}
          package: . 
          
  DeployProd:

      name: Deploy to Production 
      needs: [DeployStaging]
      runs-on: ubuntu-latest
      environment: 
       name: Production
       url: 'https://prodvenftappserver.azurewebsites.net'
      steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v2
         with:
          name: .net-app
          
       - name: Deploy to Azure Web App
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v2
         with:
          app-name: 'prodvenftappserver'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_PROD }}
          package: .        
