name: variables substitution

on: [push]
  
    
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/variable-substitution@v1
      with:
          files: 'appsettingsone.json'
      env:
       iisSettings.windowsAuthentication: ${{ secrets.WINDOWSAUTHENTICATION }}
       iisSettings.anonymousAuthentication: ${{ secrets.ANONYMOUSAUTHENTICATION }}
       iisSettings.iisExpress.applicationUrl: ${{ secrets.APPLICATIONURL }}
       iisSettings.iisExpress.sslPort: ${{ secrets.SSLPORT }}
