name: variables substitution

on: [push]

env:
  PUBLISH_PATH: '.'
    
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release -o '${{env.PUBLISH_PATH}}/publish'
    - uses: microsoft/variable-substitution@v1
      with:
          files: '${{env.PUBLISH_PATH}}/publish/appsettingsone.json'
      env:
       iisSettings.windowsAuthentication: ${{ secrets.WINDOWSAUTHENTICATION }}
       iisSettings.anonymousAuthentication: ${{ secrets.ANONYMOUSAUTHENTICATION }}
       iisSettings.iisExpress.applicationUrl: ${{ secrets.APPLICATIONURL }}
       iisSettings.iisExpress.sslPort: ${{ secrets.SSLPORT }}
